spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


app.base-url=${APP_BASE_URL:http://localhost:8080}
app.default-expiry-in-days=${APP_DEFAULT_EXPIRY_IN_DAYS:30}
app.validate-original-url=${APP_VALIDATE_ORIGINAL_URL:true}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true